#ifndef VC_PLC_FLASH_MAP_H_
#define VC_PLC_FLASH_MAP_H_

#ifdef __cplusplus
extern "C" {
#endif

#define PHOENIX_FLASH_START     0x04000000
#define MAIN_PARTITION_BASEADDR 0xc4000
#define FLASH_WRITE_SIZE        256

// The Following marco is copied from /tool/mkimage/main.c
// These marco should be the same as in /tool/mkimage/main.c
#define MAX_SOC_BIN_SIZE 0xc0000
#define BBP_IRAM_SIZE    0x38000
#define BBP_DATA1_SIZE   0xd000
#define NVRAM_SIZE       0x800
#define BBP_VER_SIZE     0x10

#define PHOENIX_FLASH_LAYOUT_IRAM_START (MAX_SOC_BIN_SIZE + MAIN_PARTITION_BASEADDR)
#define PHOENIX_FLASH_LAYOUT_IRAM_END   (PHOENIX_FLASH_LAYOUT_IRAM_START + BBP_IRAM_SIZE)
#define PHOENIX_FLASH_LAYOUT_IRAM_LEN   BBP_IRAM_SIZE

#define PHOENIX_FLASH_LAYOUT_DATA1_START PHOENIX_FLASH_LAYOUT_IRAM_END
#define PHOENIX_FLASH_LAYOUT_DATA1_END   (PHOENIX_FLASH_LAYOUT_DATA1_START + BBP_DATA1_SIZE)
#define PHOENIX_FLASH_LAYOUT_DATA1_LEN   BBP_DATA1_SIZE

#define BBP_VER_START (MAX_SOC_BIN_SIZE + MAIN_PARTITION_BASEADDR + BBP_IRAM_SIZE + BBP_DATA1_SIZE)
#define BBP_VER_END   (BBP_VER_START  + BBP_VER_SIZE)

#ifdef __cplusplus
}
#endfi

#endif /* VC_PLC_FLASH_MAP_H_ */
