#ifndef _MAGPIE2_H_
#define _MAGPIE2_H_

//#define ww(reg, val) ( *((volatile unsigned *)(reg)) = (val) )

#define AHBBASE 0x40000000
#define APBBASE 0x40040000

#define MISCBASE        APBBASE+0x00006000
	#define MISC_SRAMINT    (volatile unsigned *)(MISCBASE + 0x0000)
	#define MISC_SRAMINIT   (volatile unsigned *)(MISCBASE + 0x0004)
	#define MISC_PARERR     (volatile unsigned *)(MISCBASE + 0x0008)
	#define MISC_IREN       (volatile unsigned *)(MISCBASE + 0x000C)
	#define MISC_DUTYL      (volatile unsigned *)(MISCBASE + 0x0010)
	#define MISC_DUTYH      (volatile unsigned *)(MISCBASE + 0x0014)
	#define MISC_IRQLAT     (volatile unsigned *)(MISCBASE + 0x0018)
	#define MISC_WDTPASS    (volatile unsigned *)(MISCBASE + 0x0020)
	#define MISC_WDTEN      (volatile unsigned *)(MISCBASE + 0x0024)
	#define MISC_WDTCLR     (volatile unsigned *)(MISCBASE + 0x0028)
	#define MISC_WDTSTS     (volatile unsigned *)(MISCBASE + 0x002C)

#define MISC2BASE       APBBASE+0x00007000
	#define MISC2_FLASHWC   (volatile unsigned *)(MISC2BASE + 0x0000)
	#define MISC2_CLKSEL    (volatile unsigned *)(MISC2BASE + 0x0004)
	#define MISC2_CLKDIVH   (volatile unsigned *)(MISC2BASE + 0x0008)
	#define MISC2_CLKDIVP   (volatile unsigned *)(MISC2BASE + 0x000C)
	#define MISC2_HCLKEN    (volatile unsigned *)(MISC2BASE + 0x0010)
	#define MISC2_PCLKEN    (volatile unsigned *)(MISC2BASE + 0x0014)
	#define MISC2_DSPCLKEN  (volatile unsigned *)(MISC2BASE + 0x0018)
	#define MISC2_HCLKFREQ  (volatile unsigned *)(MISC2BASE + 0x0020)
	#define MISC2_CLKENUNLOCK  (volatile unsigned *)(MISC2BASE + 0x0028)
	#define MISC2_HSOFTRST  (volatile unsigned *)(MISC2BASE + 0x0030)
	#define MISC2_PSOFTRST  (volatile unsigned *)(MISC2BASE + 0x0034)
	#define MISC2_SOFTRSTPASS  (volatile unsigned *)(MISC2BASE + 0x0038)

#define PMUBASE         APBBASE+0x00008000
	#define PMU_DSLEEPEN     (volatile unsigned *)(PMUBASE + 0x0000)
	#define PMU_DSLEEPPASS   (volatile unsigned *)(PMUBASE + 0x0004)
	#define PMU_CONTROL      (volatile unsigned *)(PMUBASE + 0x0008)
	#define PMU_STS		        (volatile unsigned *)(PMUBASE + 0x000C)
	#define PMU_IOAOEN       (volatile unsigned *)(PMUBASE + 0x0010)
	#define PMU_IOAIE        (volatile unsigned *)(PMUBASE + 0x0014)
	#define PMU_IOADAT       (volatile unsigned *)(PMUBASE + 0x0018)
	#define PMU_IOAATT       (volatile unsigned *)(PMUBASE + 0x001C)
	#define PMU_IOAWKUEN     (volatile unsigned *)(PMUBASE + 0x0020)
	#define PMU_IOASTS       (volatile unsigned *)(PMUBASE + 0x0024)
	#define PMU_IOAINT       (volatile unsigned *)(PMUBASE + 0x0028)
	#define PMU_VERSION	      (volatile unsigned *)(PMUBASE + 0x003C)
	#define PMU_WDTPASS      (volatile unsigned *)(PMUBASE + 0x0040)
	#define PMU_WDTEN        (volatile unsigned *)(PMUBASE + 0x0044)
	#define PMU_WDTCLR       (volatile unsigned *)(PMUBASE + 0x0048)
	#define PMU_WDTSTS       (volatile unsigned *)(PMUBASE + 0x004C)
	#define PMU_IOASEL0      (volatile unsigned *)(PMUBASE + 0x0054)
	#define PMU_IOASEL1      (volatile unsigned *)(PMUBASE + 0x0058)
	#define PMU_NVRSWAP      (volatile unsigned *)(PMUBASE + 0x0060)
	#define PMU_NVRSWAPPASS  (volatile unsigned *)(PMUBASE + 0x0064)
	#define PMU_REMAP        (volatile unsigned *)(PMUBASE + 0x0068)
	#define PMU_REMAPPASS		  (volatile unsigned *)(PMUBASE + 0x006C)
	#define PMU_STRAP        (volatile unsigned *)(PMUBASE + 0x0070)
	#define PMU_VER2		      (volatile unsigned *)(PMUBASE + 0x0074)
	#define PMU_TEST1	        (volatile unsigned *)(PMUBASE + 0x00F0)
	#define PMU_POR33			   (volatile unsigned *)(PMUBASE + 0x0100)
	#define PMU_POR12			   (volatile unsigned *)(PMUBASE + 0x0104)
	#define PMU_BUCK			   (volatile unsigned *)(PMUBASE + 0x0108) 
	#define RG_RCO100K_CTRL   (volatile unsigned *)(PMUBASE + 0x100)
	#define RG_LDO_CTRL       (volatile unsigned *)(PMUBASE + 0x104)
	#define RG_BUCK_CTRL      (volatile unsigned *)(PMUBASE + 0x108)
	#define PMU_RCO100KCTRL   (volatile unsigned *)(PMUBASE + 0x200)
	#define PMU_RCO1MCTRL     (volatile unsigned *)(PMUBASE + 0x210)

#define ANABASE         APBBASE+0x0000B000
	#define RG_XTAL_CTRL		(volatile unsigned *)(ANABASE + 0x000)
	#define RG_GPPLL_CTRL0	(volatile unsigned *)(ANABASE + 0x004)
	#define RG_GPPLL_CTRL1	(volatile unsigned *)(ANABASE + 0x008)
	#define RG_FNPLL_CTRL		(volatile unsigned *)(ANABASE + 0x00C)
	#define RG_GROUP_04	    (volatile unsigned *)(ANABASE + 0x010)
	#define RG_GROUP_05	    (volatile unsigned *)(ANABASE + 0x014)
	#define RG_SOC_FNPLL_CTRL		  (volatile unsigned *)(ANABASE + 0x110)
	#define RG_SOC_FNPLL_DDSMIN		(volatile unsigned *)(ANABASE + 0x114)
	#define RG_SOC_FNPLL_OFFSETIN	(volatile unsigned *)(ANABASE + 0x118)
	#define RG_SOC_FNPLL_TESTIN		(volatile unsigned *)(ANABASE + 0x11C)
	#define RG_SOC_FNPLL_PROBE		(volatile unsigned *)(ANABASE + 0x120)
	#define RG_SOC_FNPLL_METER_CTRL (volatile unsigned *)(ANABASE + 0x124)
	#define RG_AUXSAR_CTRL   (volatile unsigned *)(ANABASE + 0x0130)
	#define ANA_ADCCTRL	     (volatile unsigned *)(ANABASE + 0x0140)
	#define ANA_ADCCHEN	     (volatile unsigned *)(ANABASE + 0x0144)
	#define ANA_ADCDATA	     (volatile unsigned *)(ANABASE + 0x0148)
	#define ANA_ADCDATA0	   (volatile unsigned *)(ANABASE + 0x0150)
	#define ANA_ADCDATA1	   (volatile unsigned *)(ANABASE + 0x0154)
	#define ANA_ADCDATA2	   (volatile unsigned *)(ANABASE + 0x0158)
	#define ANA_ADCDATA3	   (volatile unsigned *)(ANABASE + 0x015C)
	#define ANA_ADCDATA4	   (volatile unsigned *)(ANABASE + 0x0160)
	#define ANA_ADCDATA5	   (volatile unsigned *)(ANABASE + 0x0164)
	#define ANA_ADCDATA6	   (volatile unsigned *)(ANABASE + 0x0168)
	#define ANA_ADCDATA7	   (volatile unsigned *)(ANABASE + 0x016C)
	#define ANA_ADCDATA8	   (volatile unsigned *)(ANABASE + 0x0170)
	#define ANA_ADCDATA9	   (volatile unsigned *)(ANABASE + 0x0174)
	#define ANA_ADCDATA10	   (volatile unsigned *)(ANABASE + 0x0178)
	#define ANA_ADCDATA11    (volatile unsigned *)(ANABASE + 0x017C)
	#define ANA_ADCDATA12    (volatile unsigned *)(ANABASE + 0x0180)
	#define ANA_ADCDATA13    (volatile unsigned *)(ANABASE + 0x0184)
	#define ANA_ADCDATA14    (volatile unsigned *)(ANABASE + 0x0188)
	#define ANA_ADCDATA15    (volatile unsigned *)(ANABASE + 0x018C)

#endif
