#ifndef _VC_LMAC_RXH_H_
#define _VC_LMAC_RXH_H_

#include "vc_type.h"

typedef enum lmacBbpRawCmdType {
	LMAC_BBP_RAW_CMD_NONE_TYPE = 0x0000,
	LMAC_BBP_RAW_CMD_BAND_CNF = 0x1001,
	LMAC_BBP_RAW_CMD_ERROR_CNF = 0x1007,
	LMAC_BBP_RAW_CMD_RXC_CNF = 0x100F,
	LMAC_BBP_RAW_CMD_CAPTURE_PMB = 0x1036,
	LMAC_BBP_RAW_CMD_TXC_CNF = 0x1037,
	LMAC_BBP_RAW_CMD_PMB_IND=0x1045,
	LMAC_BBP_RAW_CMD_NOISE_IND = 0x1046,
	LMAC_BBP_RAW_CMD_BIT_RERVSAL_DISABLE = 0x1048,
	LMAC_BBP_RAW_CMD_FNPLL_CNF = 0x1051,
	LMAC_BBP_RAW_CMD_SNIFFER_IND = 0x1056,
	LMAC_BBP_RAW_CMD_BCN_LATE_IND = 0x1075,
	LMAC_BBP_RAW_CMD_PNM_IND = 0x107A,
	LMAC_BBP_RAW_CMD_TIMER0_PNM_IND = 0x107B,
	LMAC_BBP_RAW_CMD_NID_CNF = 0x1AA9,
	LMAC_BBP_RAW_CMD_NID_PTEI_CNF = 0x1AAA,

	LMAC_BBP_RAW_CMD_TOTAL_TYPE = 0xFFFF
}lmacBbpRawCmdType;

void lmac_receive_desc_data_ind(vc_uint8 descIdx);
void lmac_process_mac_rxq_complete(vc_uint8 dmaDescIdx);

#endif
