#ifndef DBGSTORE_CONFIG_H
#define DBGSTORE_CONFIG_H

#define DBGSTORE_ENABLE (1)
#define DBGSTORE_MSG_MAX_SIZE (48)
#define DBGSTORE_USE_MALLOC (1)
#define DBGSTORE_BASE_ADDR (0x18b000)
#define DBGSTORE_PARTITION_NUM (6)
#define DBGSTORE_PARTITION_SIZE (0x1000)
#define DBGSTORE_USE_PRINTF (0)

#endif /* DBGSTORE_CONFIG_H */
