libt2n: libt2n::t2n_exception Class Reference
libt2n::t2n_exception Class Reference
a generic exception that can be handeled with libt2n
#include <t2n_exception.hxx>
Public Member Functions
t2n_exception (const std::string &_message)
t2n_exception ()
virtual const char * what () const throw ()
virtual t2n_exception * clone () const
virtual ~t2n_exception () throw ()
virtual void do_throw ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string message
Friends
class boost::serialization::access
Detailed Description
a generic exception that can be handeled with libt2n
Note:
don't derive the exceptions your application generates directly from this one but use libt2n::t2n_runtime_error for this
Constructor & Destructor Documentation
libt2n::t2n_exception::t2n_exception (const std::string & _message) [inline]
References message.
libt2n::t2n_exception::t2n_exception () [inline]
Referenced by clone().
virtual libt2n::t2n_exception::~t2n_exception () throw () [inline, virtual]
Member Function Documentation
virtual t2n_exception* libt2n::t2n_exception::clone () const [inline, virtual]
Reimplemented in libt2n::t2n_communication_error, libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, libt2n::t2n_version_mismatch, libt2n::t2n_command_error, libt2n::t2n_serialization_error, and libt2n::t2n_runtime_error.
References t2n_exception().
Referenced by libt2n::command_server::handle_packet().
virtual void libt2n::t2n_exception::do_throw () [inline, virtual]
Reimplemented in libt2n::t2n_communication_error, libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, libt2n::t2n_version_mismatch, libt2n::t2n_command_error, libt2n::t2n_serialization_error, and libt2n::t2n_runtime_error.
template<class Archive > void libt2n::t2n_exception::serialize (Archive & ar, const unsigned int version) [private]
Reimplemented in libt2n::t2n_communication_error, libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, libt2n::t2n_version_mismatch, libt2n::t2n_command_error, libt2n::t2n_serialization_error, and libt2n::t2n_runtime_error.
virtual const char* libt2n::t2n_exception::what () const throw () [inline, virtual]
References message.
Referenced by libt2n::socket_client_connection::socket_client_connection().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented in libt2n::t2n_communication_error, libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, libt2n::t2n_version_mismatch, libt2n::t2n_command_error, libt2n::t2n_serialization_error, and libt2n::t2n_runtime_error.
Member Data Documentation
std::string libt2n::t2n_exception::message [private]
Referenced by t2n_exception(), and what().
The documentation for this class was generated from the following file:
t2n_exception.hxx
© Intra2net AG 2015 | Imprint | Contact