libt2n: libt2n::t2n_communication_error Class Reference
libt2n::t2n_communication_error Class Reference
a (unspecified) problem with libt2n communication
#include <t2n_exception.hxx>
Public Member Functions
t2n_communication_error (const std::string &_message)
t2n_communication_error ()
t2n_exception * clone () const
void do_throw ()
virtual const char * what () const throw ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
a (unspecified) problem with libt2n communication
Constructor & Destructor Documentation
libt2n::t2n_communication_error::t2n_communication_error (const std::string & _message) [inline]
libt2n::t2n_communication_error::t2n_communication_error () [inline]
Referenced by clone().
Member Function Documentation
t2n_exception* libt2n::t2n_communication_error::clone () const [inline, virtual]
Reimplemented from libt2n::t2n_exception.
Reimplemented in libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, and libt2n::t2n_version_mismatch.
References t2n_communication_error().
Referenced by libt2n::command_client::command_client().
void libt2n::t2n_communication_error::do_throw () [inline, virtual]
Reimplemented from libt2n::t2n_exception.
Reimplemented in libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, and libt2n::t2n_version_mismatch.
template<class Archive > void libt2n::t2n_communication_error::serialize (Archive & ar, const unsigned int version) [private]
Reimplemented from libt2n::t2n_exception.
Reimplemented in libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, and libt2n::t2n_version_mismatch.
virtual const char* libt2n::t2n_exception::what () const throw () [inline, virtual, inherited]
References libt2n::t2n_exception::message.
Referenced by libt2n::socket_client_connection::socket_client_connection().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from libt2n::t2n_exception.
Reimplemented in libt2n::t2n_connect_error, libt2n::t2n_server_error, libt2n::t2n_transfer_error, and libt2n::t2n_version_mismatch.
The documentation for this class was generated from the following file:
t2n_exception.hxx
© Intra2net AG 2015 | Imprint | Contact