libt2n: libt2n::t2n_runtime_error Class Reference
libt2n::t2n_runtime_error Class Reference
a runtime error within the remote function. derive your own custom exceptions from this one
#include <t2n_exception.hxx>
Public Member Functions
t2n_runtime_error (const std::string &_message)
t2n_runtime_error ()
t2n_exception * clone () const
void do_throw ()
virtual const char * what () const throw ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
a runtime error within the remote function. derive your own custom exceptions from this one
Note:
you must override the virtual clone method if you do so (used by libt2n::command_server::handle())
Constructor & Destructor Documentation
libt2n::t2n_runtime_error::t2n_runtime_error (const std::string & _message) [inline]
libt2n::t2n_runtime_error::t2n_runtime_error () [inline]
Referenced by clone().
Member Function Documentation
t2n_exception* libt2n::t2n_runtime_error::clone () const [inline, virtual]
Reimplemented from libt2n::t2n_exception.
References t2n_runtime_error().
void libt2n::t2n_runtime_error::do_throw () [inline, virtual]
Reimplemented from libt2n::t2n_exception.
template<class Archive > void libt2n::t2n_runtime_error::serialize (Archive & ar, const unsigned int version) [private]
Reimplemented from libt2n::t2n_exception.
virtual const char* libt2n::t2n_exception::what () const throw () [inline, virtual, inherited]
References libt2n::t2n_exception::message.
Referenced by libt2n::socket_client_connection::socket_client_connection().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from libt2n::t2n_exception.
The documentation for this class was generated from the following file:
t2n_exception.hxx
© Intra2net AG 2015 | Imprint | Contact